name: Deployment Check

on:
  push:
    branches: [source]
  pull_request:
  schedule:
    # Daily noon UTC, 5pm PST, 9am KST
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run check
      - run: npm run build
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
